### ISSUE TITLE
java sdk 3.0.8报错

### ISSUE THREAD

**Issue by lonehand** [tencentyun/qcloud-cos-sts-sdk#50]
Exception in thread "main" java.lang.NoSuchMethodError: org.json.JSONObject.keySet()Ljava/util/Set;
	at com.tencent.cloud.CosStsClient.downCompat(CosStsClient.java:96)
	at com.tencent.cloud.CosStsClient.getCredential(CosStsClient.java:63)

**Comment by lonehand** [comment]
排除以下依赖即可
<groupId>com.vaadin.external.google</groupId>
<artifactId>android-json</artifactId>
