### ISSUE TITLE
python 按照包时候，出现报错gbk can't decode

### ISSUE THREAD

**Issue by tangyh001** [tencentyun/qcloud-cos-sts-sdk#76]
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\tangyh\AppData\Local\Temp\pip-install-3gl6tae6\qcloud-python-sts_6a6f59637d6343ec9bc670a50b5ae11f\setup.py", line 5, in <module>
          long_description = fh.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x8b in position 82: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by xsshim** [comment]
+1

**Comment by RenLangMan** [comment]
+1
